# This file is for development/test purposes only
# Eventually this will be replaced by mock driver implementation to not require docker for dev/tests
version: '3'
services:
  postgres:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: sqlpad
      POSTGRES_DB: sqlpad
    ports: 
      - "5432:5432"